import { Thread } from '../types'

/**
 * Generate a markdown summary report of all AI feedback
 */
export function generateFeedbackReport(
  threads: Thread[],
  fileName: string,
  _code: string
): string {
  const now = new Date()
  const formattedDate = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })

  const activeThreads = threads.filter((t) => t.status === 'active')
  const resolvedThreads = threads.filter((t) => t.status === 'resolved')

  let report = `# AI Code Review Report

**File:** ${fileName}
**Generated:** ${formattedDate}
**Total Threads:** ${threads.length} (${activeThreads.length} active, ${resolvedThreads.length} resolved)

---

## Summary

`

  // Add summary statistics
  const totalMessages = threads.reduce((acc, t) => acc + t.messages.length, 0)
  const aiMessages = threads.reduce(
    (acc, t) => acc + t.messages.filter((m) => m.role === 'assistant').length,
    0
  )

  report += `- **Total conversations:** ${threads.length}
- **Total messages exchanged:** ${totalMessages}
- **AI responses:** ${aiMessages}

---

## Detailed Feedback

`

  // Add each thread's feedback
  threads.forEach((thread, index) => {
    const statusEmoji = thread.status === 'resolved' ? '✅' : '💬'
    const createdAt = new Date(thread.createdAt).toLocaleString()

    report += `### ${statusEmoji} Thread ${index + 1}: Lines ${thread.startLine}-${thread.endLine}

**Status:** ${thread.status}
**Created:** ${createdAt}

#### Selected Code

\`\`\`${thread.language}
${thread.selectedText}
\`\`\`

#### Conversation

`

    thread.messages.forEach((message) => {
      const role = message.role === 'user' ? '👤 **User**' : '🤖 **AI**'
      const time = new Date(message.timestamp).toLocaleTimeString()

      report += `${role} (${time}):

${message.content}

---

`
    })

    report += '\n'
  })

  // Add code snapshot if any suggestions were made
  const hasSuggestions = threads.some((t) =>
    t.messages.some((m) => m.suggestedCode)
  )

  if (hasSuggestions) {
    report += `## Suggested Code Changes

The following suggestions were made during the review:

`
    threads.forEach((thread) => {
      thread.messages.forEach((message) => {
        if (message.suggestedCode) {
          report += `### Suggestion for Lines ${thread.startLine}-${thread.endLine}

**Original:**
\`\`\`${thread.language}
${thread.selectedText}
\`\`\`

**Suggested:**
\`\`\`${thread.language}
${message.suggestedCode}
\`\`\`

---

`
        }
      })
    })
  }

  report += `---

*Report generated by AI Code Review Assistant*
`

  return report
}

/**
 * Generate JSON export of all feedback
 */
export function generateFeedbackJSON(
  threads: Thread[],
  fileName: string,
  code: string
): string {
  const exportData = {
    exportDate: new Date().toISOString(),
    fileName,
    codeLength: code.length,
    codeLines: code.split('\n').length,
    summary: {
      totalThreads: threads.length,
      activeThreads: threads.filter((t) => t.status === 'active').length,
      resolvedThreads: threads.filter((t) => t.status === 'resolved').length,
      totalMessages: threads.reduce((acc, t) => acc + t.messages.length, 0),
    },
    threads: threads.map((thread) => ({
      id: thread.id,
      lineRange: `${thread.startLine}-${thread.endLine}`,
      status: thread.status,
      language: thread.language,
      createdAt: new Date(thread.createdAt).toISOString(),
      selectedCode: thread.selectedText,
      messages: thread.messages.map((m) => ({
        role: m.role,
        content: m.content,
        timestamp: new Date(m.timestamp).toISOString(),
        suggestedCode: m.suggestedCode || null,
      })),
    })),
  }

  return JSON.stringify(exportData, null, 2)
}

/**
 * Download content as a file
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

